import { readFile } from 'node:fs/promises';
import { NextResponse } from 'next/server';
import { mkdir, writeFile } from 'node:fs/promises';
import { prisma } from '@buddyads/db';
import path from 'node:path';
import type { IntelligenceReport } from '@/lib/report-types';
import { renderReportPdf } from '@/lib/render-report-pdf';

export const runtime = 'nodejs';

export async function GET(
  _req: Request,
  ctx: { params: Promise<{ token: string }> },
) {
  const { token } = await ctx.params;
  const report = await prisma.report.findUnique({
    where: { token },
    select: {
      pdfPath: true,
      payload: true,
      jobId: true,
      job: { select: { customer: { select: { name: true } } } },
    },
  });

  if (!report) {
    return NextResponse.json({ message: 'PDF not found' }, { status: 404 });
  }

  const payload = report.payload;
  if (!payload) {
    return NextResponse.json({ message: 'PDF not found' }, { status: 404 });
  }

  let parsed: IntelligenceReport | null = null;
  try {
    parsed = JSON.parse(payload) as IntelligenceReport;
  } catch {
    parsed = null;
  }

  if (!parsed) {
    return NextResponse.json({ message: 'PDF not found' }, { status: 404 });
  }

  // Fast path: read the cached file if it exists.
  if (report.pdfPath) {
    try {
      const bytes = await readFile(report.pdfPath);
      return new NextResponse(bytes as any, {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="buddyads-visibility-${token.slice(0, 8)}.pdf"`,
        },
      });
    } catch {
      // Fall through to regeneration.
    }
  }

  try {
    const customerName = report.job?.customer?.name || 'Customer';
    const bytes = await renderReportPdf(parsed, customerName);

    // Best-effort cache write: keep a stable location inside the web runtime.
    // Note: if worker already wrote elsewhere, we still serve the regenerated bytes.
    const dir = path.resolve(process.cwd(), 'storage', 'pdfs');
    await mkdir(dir, { recursive: true });
    if (report.jobId) {
      const filePath = path.join(dir, `${report.jobId}.pdf`);
      await writeFile(filePath, bytes);
    }

    return new NextResponse(bytes as any, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="buddyads-visibility-${token.slice(0, 8)}.pdf"`,
      },
    });
  } catch (e) {
    return NextResponse.json(
      { message: 'PDF file missing', detail: e instanceof Error ? e.message : undefined },
      { status: 404 },
    );
  }
}

