export type RecEffort = 'S' | 'M' | 'L';
export type RecOwner = 'content' | 'dev' | 'PR';

export type RecMetadata = {
  effort: RecEffort;
  ownerType: RecOwner;
  timeToImpact: string;
};

/** Judgments — ESTIMATED. Looked up by finding id, never regenerated by the LLM. */
export const REC_METADATA: Record<string, RecMetadata> = {
  'mention-gap': { effort: 'L', ownerType: 'PR', timeToImpact: '60–90 days' },
  'citation-gap': { effort: 'M', ownerType: 'PR', timeToImpact: '30–60 days' },
  differentiation: { effort: 'M', ownerType: 'content', timeToImpact: '4–8 weeks' },
  'position-gap': { effort: 'M', ownerType: 'content', timeToImpact: '30–60 days' },
  faq: { effort: 'S', ownerType: 'content', timeToImpact: '2–4 weeks' },
  thin: { effort: 'M', ownerType: 'content', timeToImpact: '3–6 weeks' },
  'product-schema': { effort: 'S', ownerType: 'dev', timeToImpact: '1–3 weeks' },
  entity: { effort: 'S', ownerType: 'dev', timeToImpact: '1–2 weeks' },
  comparison: { effort: 'M', ownerType: 'content', timeToImpact: '3–6 weeks' },
  author: { effort: 'S', ownerType: 'content', timeToImpact: '2–4 weeks' },
  location: { effort: 'S', ownerType: 'dev', timeToImpact: '1–3 weeks' },
  about: { effort: 'S', ownerType: 'content', timeToImpact: '1–3 weeks' },
  links: { effort: 'S', ownerType: 'content', timeToImpact: '2–4 weeks' },
  questions: { effort: 'S', ownerType: 'content', timeToImpact: '2–4 weeks' },
  sitemap: { effort: 'S', ownerType: 'dev', timeToImpact: '3–7 days' },
};

export const REC_METADATA_DEFAULT: RecMetadata = {
  effort: 'M',
  ownerType: 'content',
  timeToImpact: '30–45 days',
};

export function recMetadataFor(findingId: string): RecMetadata {
  return REC_METADATA[findingId] || REC_METADATA_DEFAULT;
}

export const NO_CATEGORY_BENCHMARK = {
  available: false as const,
  note: 'No benchmark available for this category',
  typicalMentionRate: null as number | null,
  strongMentionRate: null as number | null,
};
